### ISSUE TITLE
Logo for the marketplace

### ISSUE THREAD

**Issue by paulvi** [de-jcup/jcup-eclipse-plugins-collection#7]
Should be a logo for all this plugins put together

It can be like

![image](https://user-images.githubusercontent.com/1614482/40709523-db595db0-6428-11e8-8ddd-eef96c2eddfd.png)

to hint to

![](https://marketplace.eclipse.org/sites/default/files/styles/ds_medium/public/EGradle-Profile-Image-Marketplace.png)![](https://marketplace.eclipse.org/sites/default/files/styles/ds_medium/public/EGradle-Profile-Image-Editor-Marketplace.png)![](https://marketplace.eclipse.org/sites/default/files/styles/ds_medium/public/bash-editor-logo.png)![](https://marketplace.eclipse.org/sites/default/files/styles/ds_medium/public/batch-editor-logo.png)![](https://marketplace.eclipse.org/sites/default/files/styles/ds_medium/public/asciidoctor-editor-logo_0.png)![](https://marketplace.eclipse.org/sites/default/files/styles/ds_medium/public/jenkins-editor-logo.png)![](https://marketplace.eclipse.org/sites/default/files/styles/ds_medium/public/yaml-editor-logo.png)

**Comment by de-jcup** [comment]
Thank you for the idea about the logo. I will upload something in this way.

**Comment by de-jcup** [comment]
Uploaded icon to marketplace.
